Fix loading peer certificates for corporate networks (#83)
Currently when running SVM on a corporate style network that uses a peer
certificate you will get an error because it won't automatically be
recognised. The error looks like this

```
./svm list
Error: error sending request for url (https://github.com/roynalnaruto/solc-builds/raw/240988f6e5de44fd182a9d4446a838cb7b7166db/macosx/aarch64/list.json): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Caused by:
    0: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
    1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

This PR includes the `rustls-tls-native-roots` feature in `reqwest` so
that peer certificates can be included which will prevent the error.

This is my first PR on this repo and I'm fairly new to rust so please
let me know if I've missed anything, thanks.

---------

Co-authored-by: evalir <hi@enriqueortiz.dev>
Co-authored-by: DaniPopes <57450786+DaniPopes@users.noreply.github.com>